config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'reminders#index'

  resources :reminders
  devise_for :users

  authenticate :user, ->(u) { u.current_sign_in_ip? } do
    require 'sidekiq/web'
    require 'sidekiq/cron/web'
    mount Sidekiq::Web => '/sidekiq'
    mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(_user)
    can :manage, :all
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current.rb
# frozen_string_literal: true

# app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/reminder.rb
# frozen_string_literal: true

# Reminder Model
class Reminder < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :description, presence: true
  validates :day_of_month, presence: true, numericality: { only_integer: true }, inclusion: { in: 1..31 }
  validates :time_of_day, presence: true

  after_save do
    Sidekiq::Cron::Job.create(
      name: "reminder_#{id}",
      cron: cron,
      class: 'SchedulerWorker',
      args: [ user.email, title, description ]
    )
  end

  after_destroy do
    Sidekiq::Cron::Job.destroy "reminder_#{id}"
  end

  scope :by_owner, -> { where(user_id: Current.user.id) }

  private

  def cron
    "#{time_of_day.min} #{time_of_day.hour} #{day_of_month} * *"
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :two_factor_authenticatable,
         :confirmable, :lockable, :timeoutable, :trackable, :omniauthable,
         :registerable, :recoverable, :rememberable, :validatable

  devise otp_secret_encryption_key: ENV['2FA_ENCRYPTION_KEY']

  has_many :reminders
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# ApplicationController
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action do
    if (Current.user = current_user)
      Rack::MiniProfiler.authorize_request unless Rails.env.test?
    end
  end

  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { head :forbidden, content_type: 'text/html' }
      format.html { redirect_to root_path, notice: exception.message }
      format.js   { head :forbidden, content_type: 'text/html' }
    end
  end
end

app/controllers/reminders_controller.rb
# frozen_string_literal: true

class RemindersController < ApplicationController
  load_and_authorize_resource
  # before_action :set_reminder, only: %i[show edit update destroy]

  # GET /reminders
  # GET /reminders.json
  def index
    @reminders = Reminder.by_owner.order(:created_at)
  end

  # GET /reminders/1
  # GET /reminders/1.json
  def show; end

  # GET /reminders/new
  def new
    @reminder = Reminder.new
  end

  # GET /reminders/1/edit
  def edit; end

  # POST /reminders
  # POST /reminders.json
  def create
    @reminder = Reminder.new(reminder_params)

    respond_to do |format|
      if @reminder.save
        format.html { redirect_to @reminder, notice: 'Reminder was successfully created.' }
        format.json { render :show, status: :created, location: @reminder }
      else
        format.html { render :new }
        format.json { render json: @reminder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reminders/1
  # PATCH/PUT /reminders/1.json
  def update
    respond_to do |format|
      if @reminder.update(reminder_params)
        format.html { redirect_to @reminder, notice: 'Reminder was successfully updated.' }
        format.json { render :show, status: :ok, location: @reminder }
      else
        format.html { render :edit }
        format.json { render json: @reminder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reminders/1
  # DELETE /reminders/1.json
  def destroy
    @reminder.destroy
    respond_to do |format|
      format.html { redirect_to reminders_url, notice: 'Reminder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_reminder
    @reminder = Reminder.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def reminder_params
    params.require(:reminder).permit(:title, :description, :day_of_month, :time_of_day).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/reminders_helper.rb
# frozen_string_literal: true

module RemindersHelper
  def options_for_day_select
    Array.new(31) do |day|
      case day
      when 0, 1, 2
        ["#{(day + 1).ordinalize} Day of Month", day + 1]
      when 28, 29
        ["#{(31 - day).ordinalize} last Day of Month", day + 1]
      when 30
        ['Last Day of Month', day + 1]
      else
        [(day + 1).to_s, day + 1]
      end
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Evopark</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/reminders/_form.html.erb
<% if reminder.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(reminder.errors.count, "error") %> prohibited this reminder from being saved:</h2>

    <ul>
    <% reminder.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
    
<div class="card-body">
  <%= form_with(model: reminder, local: true, class: 'form-horizontal') do |form| %>
    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, class: 'form-control', type: 'text' %>
    </div>

    <div class="form-group">
      <%= form.label :description %>
      <%= form.text_area :description, class: 'form-control', type: 'text' %>
    </div>

    <div class="form-group">
      <%= form.label :day_of_month %>
      <%= form.select :day_of_month, options_for_day_select, class: 'selectpicker form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :time_of_day %>
      <%= form.time_select :time_of_day, class: 'form-control' %>
    </div>

    <div class="actions">
      <%= form.submit class: 'btn btn-info' %>
    </div>
<% end %>
</div>

app/views/reminders/edit.html.erb
<h1>Editing Reminder - <%= @reminder.title %></h1>
<div class='card'>
	<%= render 'form', reminder: @reminder %>
</div>
<%= link_to 'Back', reminders_path, class: 'btn btn-secondary' %>
<%= link_to 'Show', @reminder, class: 'btn btn-secondary float-right' %>

app/views/reminders/index.html.erb
<h1>Reminders</h1>
<p id="notice"><%= notice %></p>
<div class='card'>
  <table class='table'>
    <thead>
      <tr>
        <th>Title</th>
        <th>Message</th>
        <th>DoM</th>
        <th>ToD</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @reminders.each do |reminder| %>
        <tr>
          <td><%= reminder.title %></td>
          <td><%= reminder.description %></td>
          <td><%= reminder.day_of_month %></td>
          <td><%= reminder.time_of_day.strftime('%H:%M:%S') %> o'clock</td>
          <td><%= link_to 'Show', reminder, class: 'btn-sm btn-info' %></td>
          <td><%= link_to 'Edit', edit_reminder_path(reminder), class: 'btn-sm btn-info' %></td>
          <td><%= link_to 'Destroy', reminder, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn-sm btn-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= link_to 'New Reminder', new_reminder_path, class: 'btn btn-secondary' %>

app/views/reminders/new.html.erb
<h1>New Reminder</h1>
<div class='card'>
	<%= render 'form', reminder: @reminder %>
</div>
<%= link_to 'Back', reminders_path, class: 'btn btn-secondary' %>

app/views/reminders/show.html.erb
<h1><%= "Overview Reminder - #{@reminder.title}" %></h1>
<p id="notice"><%= notice %></p>
<div class='card'>
	<p>
	  <strong>Title:</strong>
	  <%= @reminder.title %>
	</p>

	<p>
	  <strong>Message:</strong>
	  <%= @reminder.description %>
	</p>

	<p>
	  <strong>Day of Month:</strong>
	  <%= @reminder.day_of_month %>
	</p>

	<p>
	  <strong>Time of Day:</strong>
	  <%= @reminder.time_of_day.strftime('%H:%M o\'clock') %>
	</p>
</div>
<%= link_to 'Back', reminders_path, class: 'btn btn-secondary' %>
<%= link_to 'Edit', edit_reminder_path(@reminder), class: 'float-right btn btn-secondary' %>